// Code generated by protoc-gen-go. DO NOT EDIT.
// source: party.proto

package party_v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Party_Gender int32

const (
	Party_MALE   Party_Gender = 0
	Party_FEMALE Party_Gender = 1
)

var Party_Gender_name = map[int32]string{
	0: "MALE",
	1: "FEMALE",
}

var Party_Gender_value = map[string]int32{
	"MALE":   0,
	"FEMALE": 1,
}

func (x Party_Gender) String() string {
	return proto.EnumName(Party_Gender_name, int32(x))
}

func (Party_Gender) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f8c47bfae09949f0, []int{0, 0}
}

type Party_PhoneType int32

const (
	Party_MOBILE Party_PhoneType = 0
	Party_HOME   Party_PhoneType = 1
	Party_WORK   Party_PhoneType = 2
)

var Party_PhoneType_name = map[int32]string{
	0: "MOBILE",
	1: "HOME",
	2: "WORK",
}

var Party_PhoneType_value = map[string]int32{
	"MOBILE": 0,
	"HOME":   1,
	"WORK":   2,
}

func (x Party_PhoneType) String() string {
	return proto.EnumName(Party_PhoneType_name, int32(x))
}

func (Party_PhoneType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f8c47bfae09949f0, []int{0, 1}
}

type Party struct {
	FirstName            string               `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string               `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Gender               Party_Gender         `protobuf:"varint,3,opt,name=gender,proto3,enum=party.v1.Party_Gender" json:"gender,omitempty"`
	DataOfBirth          string               `protobuf:"bytes,4,opt,name=dataOfBirth,proto3" json:"dataOfBirth,omitempty"`
	Phones               []*Party_PhoneNumber `protobuf:"bytes,5,rep,name=phones,proto3" json:"phones,omitempty"`
	Email                string               `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	AddressLine1         string               `protobuf:"bytes,7,opt,name=addressLine1,proto3" json:"addressLine1,omitempty"`
	AddressLine2         string               `protobuf:"bytes,8,opt,name=addressLine2,proto3" json:"addressLine2,omitempty"`
	AddressLine3         string               `protobuf:"bytes,9,opt,name=addressLine3,proto3" json:"addressLine3,omitempty"`
	PinCode              int32                `protobuf:"varint,10,opt,name=pinCode,proto3" json:"pinCode,omitempty"`
	City                 string               `protobuf:"bytes,11,opt,name=city,proto3" json:"city,omitempty"`
	Latitude             float64              `protobuf:"fixed64,12,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64              `protobuf:"fixed64,13,opt,name=longitude,proto3" json:"longitude,omitempty"`
	PanNumber            string               `protobuf:"bytes,14,opt,name=panNumber,proto3" json:"panNumber,omitempty"`
	Aadhaar              int64                `protobuf:"varint,15,opt,name=aadhaar,proto3" json:"aadhaar,omitempty"`
	Id                   int64                `protobuf:"varint,16,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Party) Reset()         { *m = Party{} }
func (m *Party) String() string { return proto.CompactTextString(m) }
func (*Party) ProtoMessage()    {}
func (*Party) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8c47bfae09949f0, []int{0}
}

func (m *Party) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Party.Unmarshal(m, b)
}
func (m *Party) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Party.Marshal(b, m, deterministic)
}
func (m *Party) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Party.Merge(m, src)
}
func (m *Party) XXX_Size() int {
	return xxx_messageInfo_Party.Size(m)
}
func (m *Party) XXX_DiscardUnknown() {
	xxx_messageInfo_Party.DiscardUnknown(m)
}

var xxx_messageInfo_Party proto.InternalMessageInfo

func (m *Party) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Party) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Party) GetGender() Party_Gender {
	if m != nil {
		return m.Gender
	}
	return Party_MALE
}

func (m *Party) GetDataOfBirth() string {
	if m != nil {
		return m.DataOfBirth
	}
	return ""
}

func (m *Party) GetPhones() []*Party_PhoneNumber {
	if m != nil {
		return m.Phones
	}
	return nil
}

func (m *Party) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Party) GetAddressLine1() string {
	if m != nil {
		return m.AddressLine1
	}
	return ""
}

func (m *Party) GetAddressLine2() string {
	if m != nil {
		return m.AddressLine2
	}
	return ""
}

func (m *Party) GetAddressLine3() string {
	if m != nil {
		return m.AddressLine3
	}
	return ""
}

func (m *Party) GetPinCode() int32 {
	if m != nil {
		return m.PinCode
	}
	return 0
}

func (m *Party) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Party) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Party) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Party) GetPanNumber() string {
	if m != nil {
		return m.PanNumber
	}
	return ""
}

func (m *Party) GetAadhaar() int64 {
	if m != nil {
		return m.Aadhaar
	}
	return 0
}

func (m *Party) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Party_PhoneNumber struct {
	Number               string          `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Type                 Party_PhoneType `protobuf:"varint,2,opt,name=type,proto3,enum=party.v1.Party_PhoneType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Party_PhoneNumber) Reset()         { *m = Party_PhoneNumber{} }
func (m *Party_PhoneNumber) String() string { return proto.CompactTextString(m) }
func (*Party_PhoneNumber) ProtoMessage()    {}
func (*Party_PhoneNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8c47bfae09949f0, []int{0, 0}
}

func (m *Party_PhoneNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Party_PhoneNumber.Unmarshal(m, b)
}
func (m *Party_PhoneNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Party_PhoneNumber.Marshal(b, m, deterministic)
}
func (m *Party_PhoneNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Party_PhoneNumber.Merge(m, src)
}
func (m *Party_PhoneNumber) XXX_Size() int {
	return xxx_messageInfo_Party_PhoneNumber.Size(m)
}
func (m *Party_PhoneNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_Party_PhoneNumber.DiscardUnknown(m)
}

var xxx_messageInfo_Party_PhoneNumber proto.InternalMessageInfo

func (m *Party_PhoneNumber) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *Party_PhoneNumber) GetType() Party_PhoneType {
	if m != nil {
		return m.Type
	}
	return Party_MOBILE
}

type PartyRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Party                *Party   `protobuf:"bytes,2,opt,name=party,proto3" json:"party,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PartyRequest) Reset()         { *m = PartyRequest{} }
func (m *PartyRequest) String() string { return proto.CompactTextString(m) }
func (*PartyRequest) ProtoMessage()    {}
func (*PartyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8c47bfae09949f0, []int{1}
}

func (m *PartyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartyRequest.Unmarshal(m, b)
}
func (m *PartyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartyRequest.Marshal(b, m, deterministic)
}
func (m *PartyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartyRequest.Merge(m, src)
}
func (m *PartyRequest) XXX_Size() int {
	return xxx_messageInfo_PartyRequest.Size(m)
}
func (m *PartyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PartyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PartyRequest proto.InternalMessageInfo

func (m *PartyRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *PartyRequest) GetParty() *Party {
	if m != nil {
		return m.Party
	}
	return nil
}

type PartyResponse struct {
	Party                *Party   `protobuf:"bytes,1,opt,name=party,proto3" json:"party,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PartyResponse) Reset()         { *m = PartyResponse{} }
func (m *PartyResponse) String() string { return proto.CompactTextString(m) }
func (*PartyResponse) ProtoMessage()    {}
func (*PartyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8c47bfae09949f0, []int{2}
}

func (m *PartyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartyResponse.Unmarshal(m, b)
}
func (m *PartyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartyResponse.Marshal(b, m, deterministic)
}
func (m *PartyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartyResponse.Merge(m, src)
}
func (m *PartyResponse) XXX_Size() int {
	return xxx_messageInfo_PartyResponse.Size(m)
}
func (m *PartyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PartyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PartyResponse proto.InternalMessageInfo

func (m *PartyResponse) GetParty() *Party {
	if m != nil {
		return m.Party
	}
	return nil
}

func init() {
	proto.RegisterEnum("party.v1.Party_Gender", Party_Gender_name, Party_Gender_value)
	proto.RegisterEnum("party.v1.Party_PhoneType", Party_PhoneType_name, Party_PhoneType_value)
	proto.RegisterType((*Party)(nil), "party.v1.Party")
	proto.RegisterType((*Party_PhoneNumber)(nil), "party.v1.Party.PhoneNumber")
	proto.RegisterType((*PartyRequest)(nil), "party.v1.PartyRequest")
	proto.RegisterType((*PartyResponse)(nil), "party.v1.PartyResponse")
}

func init() { proto.RegisterFile("party.proto", fileDescriptor_f8c47bfae09949f0) }

var fileDescriptor_f8c47bfae09949f0 = []byte{
	// 490 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x61, 0x6b, 0xdb, 0x30,
	0x10, 0x9d, 0x92, 0xd8, 0x75, 0xce, 0x6d, 0x1a, 0x8e, 0x51, 0xb4, 0x6c, 0x0c, 0x63, 0x18, 0x18,
	0xc6, 0x0c, 0xb5, 0x21, 0xdf, 0xd7, 0x92, 0x65, 0x63, 0x4d, 0x53, 0xbc, 0x8e, 0x7d, 0x56, 0x2b,
	0xb5, 0x11, 0x24, 0xb6, 0x66, 0x2b, 0x85, 0xfc, 0x98, 0xfd, 0x8a, 0xfd, 0xc1, 0x61, 0xc9, 0x49,
	0x3a, 0x77, 0x0c, 0xfa, 0xed, 0xde, 0xbd, 0x77, 0x4f, 0xcf, 0x3a, 0x0b, 0x7c, 0xc5, 0x4a, 0xbd,
	0x89, 0x55, 0x59, 0xe8, 0x02, 0x3d, 0x0b, 0x1e, 0x4e, 0xc3, 0x5f, 0x0e, 0x38, 0x57, 0x35, 0xc0,
	0x37, 0xd0, 0xbf, 0x93, 0x65, 0xa5, 0x2f, 0xd9, 0x4a, 0x50, 0x12, 0x90, 0xa8, 0x9f, 0xed, 0x1b,
	0x38, 0x02, 0x6f, 0xc9, 0x1a, 0xb2, 0x63, 0xc8, 0x1d, 0xc6, 0x18, 0xdc, 0x7b, 0x91, 0x73, 0x51,
	0xd2, 0x6e, 0x40, 0xa2, 0x41, 0x72, 0x12, 0x6f, 0xed, 0x63, 0x63, 0x1d, 0x4f, 0x0d, 0x9b, 0x35,
	0x2a, 0x0c, 0xc0, 0xe7, 0x4c, 0xb3, 0xf9, 0xdd, 0x99, 0x2c, 0xf5, 0x82, 0xf6, 0x8c, 0xdd, 0xe3,
	0x16, 0xa6, 0xe0, 0xaa, 0x45, 0x91, 0x8b, 0x8a, 0x3a, 0x41, 0x37, 0xf2, 0x93, 0xd7, 0x6d, 0xc7,
	0xab, 0x9a, 0xbd, 0x5c, 0xaf, 0x6e, 0x6a, 0x5b, 0x2b, 0xc5, 0x97, 0xe0, 0x88, 0x15, 0x93, 0x4b,
	0xea, 0x1a, 0x43, 0x0b, 0x30, 0x84, 0x43, 0xc6, 0x79, 0x29, 0xaa, 0xea, 0x42, 0xe6, 0xe2, 0x94,
	0x1e, 0x18, 0xf2, 0xaf, 0x5e, 0x4b, 0x93, 0x50, 0xef, 0x89, 0x26, 0x69, 0x69, 0x52, 0xda, 0x7f,
	0xa2, 0x49, 0x91, 0xc2, 0x81, 0x92, 0xf9, 0x79, 0xc1, 0x05, 0x85, 0x80, 0x44, 0x4e, 0xb6, 0x85,
	0x88, 0xd0, 0xbb, 0x95, 0x7a, 0x43, 0x7d, 0x33, 0x65, 0x6a, 0x7b, 0xa5, 0x5a, 0xea, 0x35, 0x17,
	0xf4, 0x30, 0x20, 0x11, 0xc9, 0x76, 0xb8, 0x5e, 0xc6, 0xb2, 0xc8, 0xef, 0x2d, 0x79, 0x64, 0xc8,
	0x7d, 0xa3, 0x66, 0x15, 0xcb, 0xed, 0xe7, 0xd3, 0x81, 0x5d, 0xd5, 0xae, 0x51, 0xa7, 0x60, 0x8c,
	0x2f, 0x18, 0x2b, 0xe9, 0x71, 0x40, 0xa2, 0x6e, 0xb6, 0x85, 0x38, 0x80, 0x8e, 0xe4, 0x74, 0x68,
	0x9a, 0x1d, 0xc9, 0x47, 0xd7, 0xe0, 0x3f, 0xba, 0x48, 0x3c, 0x01, 0x37, 0xb7, 0x9e, 0x76, 0xfd,
	0x0d, 0xc2, 0x0f, 0xd0, 0xd3, 0x1b, 0x65, 0xf7, 0x3e, 0x48, 0x5e, 0xfd, 0x73, 0x17, 0xd7, 0x1b,
	0x25, 0x32, 0x23, 0x0b, 0xdf, 0x82, 0x6b, 0x17, 0x8e, 0x1e, 0xf4, 0x66, 0x1f, 0x2f, 0x26, 0xc3,
	0x17, 0x08, 0xe0, 0x7e, 0x9a, 0x98, 0x9a, 0x84, 0xef, 0xa1, 0xbf, 0x1b, 0xa9, 0x89, 0xd9, 0xfc,
	0xec, 0x8b, 0x11, 0x79, 0xd0, 0xfb, 0x3c, 0x9f, 0x4d, 0x86, 0xa4, 0xae, 0x7e, 0xcc, 0xb3, 0xaf,
	0xc3, 0x4e, 0x38, 0x85, 0x43, 0x73, 0x4a, 0x26, 0x7e, 0xae, 0x45, 0xa5, 0x71, 0x08, 0x5d, 0xa6,
	0x64, 0x13, 0xb0, 0x2e, 0xf1, 0x1d, 0x38, 0x26, 0x90, 0x89, 0xe7, 0x27, 0xc7, 0xad, 0x78, 0x99,
	0x65, 0xc3, 0x31, 0x1c, 0x35, 0x46, 0x95, 0x2a, 0xf2, 0x4a, 0xec, 0xe7, 0xc8, 0xff, 0xe6, 0x92,
	0xdf, 0xa4, 0x49, 0xf0, 0x4d, 0x94, 0x0f, 0xf2, 0x56, 0xe0, 0x18, 0xfc, 0xf3, 0x52, 0x30, 0x2d,
	0xec, 0xb3, 0x69, 0xff, 0xec, 0x4d, 0xd0, 0x51, 0xdb, 0x0f, 0x53, 0xf0, 0xa6, 0x42, 0x3f, 0x73,
	0x68, 0x0c, 0xfe, 0x77, 0xc5, 0x9f, 0x7d, 0xd8, 0x8d, 0x6b, 0xde, 0x79, 0xfa, 0x27, 0x00, 0x00,
	0xff, 0xff, 0x7b, 0xdf, 0x0a, 0xdb, 0xf6, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PartyServiceClient is the client API for PartyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PartyServiceClient interface {
	CreateParty(ctx context.Context, in *PartyRequest, opts ...grpc.CallOption) (*Party, error)
	GetParty(ctx context.Context, in *PartyRequest, opts ...grpc.CallOption) (*Party, error)
	UpdateParty(ctx context.Context, in *PartyRequest, opts ...grpc.CallOption) (*Party, error)
}

type partyServiceClient struct {
	cc *grpc.ClientConn
}

func NewPartyServiceClient(cc *grpc.ClientConn) PartyServiceClient {
	return &partyServiceClient{cc}
}

func (c *partyServiceClient) CreateParty(ctx context.Context, in *PartyRequest, opts ...grpc.CallOption) (*Party, error) {
	out := new(Party)
	err := c.cc.Invoke(ctx, "/party.v1.PartyService/CreateParty", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partyServiceClient) GetParty(ctx context.Context, in *PartyRequest, opts ...grpc.CallOption) (*Party, error) {
	out := new(Party)
	err := c.cc.Invoke(ctx, "/party.v1.PartyService/GetParty", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partyServiceClient) UpdateParty(ctx context.Context, in *PartyRequest, opts ...grpc.CallOption) (*Party, error) {
	out := new(Party)
	err := c.cc.Invoke(ctx, "/party.v1.PartyService/UpdateParty", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PartyServiceServer is the server API for PartyService service.
type PartyServiceServer interface {
	CreateParty(context.Context, *PartyRequest) (*Party, error)
	GetParty(context.Context, *PartyRequest) (*Party, error)
	UpdateParty(context.Context, *PartyRequest) (*Party, error)
}

// UnimplementedPartyServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPartyServiceServer struct {
}

func (*UnimplementedPartyServiceServer) CreateParty(ctx context.Context, req *PartyRequest) (*Party, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateParty not implemented")
}
func (*UnimplementedPartyServiceServer) GetParty(ctx context.Context, req *PartyRequest) (*Party, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetParty not implemented")
}
func (*UnimplementedPartyServiceServer) UpdateParty(ctx context.Context, req *PartyRequest) (*Party, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParty not implemented")
}

func RegisterPartyServiceServer(s *grpc.Server, srv PartyServiceServer) {
	s.RegisterService(&_PartyService_serviceDesc, srv)
}

func _PartyService_CreateParty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartyServiceServer).CreateParty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/party.v1.PartyService/CreateParty",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartyServiceServer).CreateParty(ctx, req.(*PartyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartyService_GetParty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartyServiceServer).GetParty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/party.v1.PartyService/GetParty",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartyServiceServer).GetParty(ctx, req.(*PartyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartyService_UpdateParty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartyServiceServer).UpdateParty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/party.v1.PartyService/UpdateParty",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartyServiceServer).UpdateParty(ctx, req.(*PartyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PartyService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "party.v1.PartyService",
	HandlerType: (*PartyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateParty",
			Handler:    _PartyService_CreateParty_Handler,
		},
		{
			MethodName: "GetParty",
			Handler:    _PartyService_GetParty_Handler,
		},
		{
			MethodName: "UpdateParty",
			Handler:    _PartyService_UpdateParty_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "party.proto",
}
